[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Secrets-Scanner"
version = "0.1.0"
description = "Fast, lightweight secret scanner for developers."
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.9"
authors = [
    { name = "Guilherme" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Environment :: Console",
]

[project.urls]
Homepage = "https://github.com/guicomsonin/Secret-Scanner"
Repository = "https://github.com/guicomsonin/Secret-Scanner"
Issues = "https://github.com/guicomsonin/Secret-Scanner/issues"

[project.scripts]
secretscanner = "secretscanner.cli:main"

[tool.setuptools.packages.find]
include = ["secretscanner*"]
